did dock
docknetwork/react-native-sdk pull request #56
Opened 2022-07-29 15:35 UTC by maycon-mello

2022-08-05 17:33 UTC, osinakayah commented
@maycon-mello 
Do we need a function for calculating the transaction fee needed for create a did:dock?

2022-08-06 12:00 UTC, osinakayah requested changes

2022-08-06 12:00 UTC, osinakayah commented on packages/core/lib/services/dids/index.test.js
>    it('expect to register did dock', async () => {
Can we include another test case for when something goes wrong.
Like, if no Keypair was found, or if there is insufficient for the transaction fee.

2022-08-08 14:47 UTC, maycon-mello commented
> @maycon-mello Do we need a function for calculating the transaction fee needed for create a did:dock?

I can add one in a separate PR

2022-08-09 16:55 UTC, osinakayah commented
Some tests are failing.

2022-08-10 15:09 UTC, maycon-mello commented
The failed tests seems related to the substrate mock, I'm working to fix that. Also, its showing as passing in the CI again, but shouldn't

2022-08-10 16:53 UTC, osinakayah approved these changes

2022-08-10 16:54 UTC, merged